## 데이터 준비

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
A_salary   = pd.Series([25, 28, 50, 60, 30, 35, 40, 70, 40, 70, 40, 100, 30, 30 ])
B_salary   = pd.Series([20, 40, 25, 25, 35, 25 ,20, 10, 55, 65, 100, 100, 150, 300])

In [ ]:
df = pd.DataFrame ( {'A_salary': A_salary,
                     'B_salary' :B_salary  }
)

## 대푯값 탐색

#### 평균 - mean()

In [ ]:
print("A 기업 연봉평균", A_salary.mean() , "  B 기업 연봉평균 ", B_salary.mean() )

A 기업 연봉평균 46.285714285714285   B 기업 연봉평균  69.28571428571429

In [ ]:
A_salary.mean( )
A_salary.sum()/A_salary.count()

46.285714285714285

In [ ]:
df.mean(axis=0)  #열별 평균

A_salary    46.285714
B_salary    69.285714
dtype: float64

In [ ]:
A_salary  = pd.Series([np.nan , 25, 28, 50, 60, 30, 35, 40, 70, 40, 70, 40, 100, 30, 30 ])

In [ ]:
A_salary.mean( skipna=True )  #열별 평균 .  결측치 제외

46.285714285714285

#### 중앙값 - median()

In [ ]:
A_salary   = pd.Series([25, 28, 50, 60, 30, 35, 40, 70, 40, 70, 40, 100, 30, 30 ])
B_salary   = pd.Series([20, 40, 25, 25, 35, 25 ,20, 10, 55, 65, 100, 100, 150, 300])

In [ ]:
print("A 기업 연봉 중앙값 ",  A_salary.median()  , "   B 기업 연봉 중앙값 ", B_salary.median()  )

A 기업 연봉 중앙값  40.0    B 기업 연봉 중앙값  37.5

In [ ]:
df.median(axis=0)  #열별 중앙값

A_salary    40.0
B_salary    37.5
dtype: float64

## 분산도 탐색

#### 범위 : 최대값 -  최소값

In [ ]:
A_salary.max() - A_salary.min()

75

In [ ]:
B_salary.max() - B_salary.min()

290

#### 분산  var(),    표준편차  std()

In [ ]:
A_salary.std()

21.556468140243165

In [ ]:
A_salary.var()

464.68131868131866

In [ ]:
B_salary.std()

77.53056823594814

In [ ]:
B_salary.var()

6010.989010989011